- name: Initial Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure L3 Interface
      ios_command:
        commands:
          - configure terminal
          - interface Ethernet0/1.101
          - ip address 10.100.101.253 255.255.255.0
          - no shutdown
      register: show_result

    - name: Debug registered var
      debug: var=show_result.stdout_lines
