- name: Initial Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure L3 Interface
      ios_config:
        parents:
          - interface Ethernet0/1.101
        lines:
          - encapsulation dot1Q 3
          - ip address 180.100.101.253 255.255.255.0
          - description rogi da nogi
        after:
          - end
          - write memory
        backup: yes
      register: show_result

    - name: Debug registered var
      debug: var=show_result.stdout_lines
