---

  - name: SHOW VERSION
    hosts: routers
    gather_facts: false
    connection: network_cli

    tasks:
      - name: run the command 'show version'
        ios_command:
          commands: show version